#!/bin/sh -x
# prerm script for hd44780-i2c

set -e

echo "Hello prerm called with $1" 

case "$1" in
    remove|upgrade|deconfigure|failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


exit 0
